services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - ~/volumes/devandreio/postgresql/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=devandre
    ports:
      - "127.0.0.1:5432:5432"
